apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiwoo-backend
  # namespace는 배포 시 -n jiwoo 옵션으로 지정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jiwoo-backend
  template:
    metadata:
      labels:
        app: jiwoo-backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: backend
        image: ktech4.azurecr.io/kltecho_jiwoo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "jiwoo-mariadb"
        - name: MYSQL_USER
          value: "jiwoo"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jiwoo-backend-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "jiwoo_db"
        - name: REDIS_HOST
          value: "jiwoo-redis-master"
        - name: KAFKA_SERVERS
          value: "jiwoo-kafka:9092"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jiwoo-backend-secrets
              key: REDIS_PASSWORD
        - name: KAFKA_USERNAME
          value: "user1"
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jiwoo-backend-secrets
              key: KAFKA_PASSWORD
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jiwoo-backend-secrets
              key: FLASK_SECRET_KEY
        # OpenTelemetry 환경변수 추가
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://collector.lgtm.20.249.154.255.nip.io:4318"
        - name: OTEL_SERVICE_NAME
          value: "jiwoo-backend"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=jiwoo-backend,service.version=1.0.0,deployment.environment=production"
        - name: LOG_LEVEL
          value: "INFO"
        # OTLP 로그 전송 환경변수 추가
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://collector.lgtm.20.249.154.255.nip.io:4318/v1/logs"
---
apiVersion: v1
kind: Service
metadata:
  name: jiwoo-backend-service
  # namespace는 배포 시 -n jiwoo 옵션으로 지정
spec:
  type: ClusterIP
  selector:
    app: jiwoo-backend
  ports:
  - port: 5000
    targetPort: 5000
