apiVersion: batch/v1
kind: Job
metadata:
  name: jiwoo-mariadb-init
  # namespace는 배포 시 -n jiwoo 옵션으로 지정
spec:
  template:
    spec:
      containers:
      - name: mariadb-init
        image: docker.io/bitnami/mariadb:12.0.2-debian-12-r0
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for MariaDB to be ready..."
          until mysql -h jiwoo-mariadb -u jiwoo -pjiwoo1234! -e "SELECT 1"; do
            sleep 5
          done
          
          echo "Creating database and tables..."
          mysql -h jiwoo-mariadb -u jiwoo -pjiwoo1234! << 'EOF'
          CREATE DATABASE IF NOT EXISTS jiwoo_db;
          USE jiwoo_db;
          
          CREATE TABLE IF NOT EXISTS users (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(255) UNIQUE NOT NULL,
              password VARCHAR(255) NOT NULL,
              created_at DATETIME DEFAULT CURRENT_TIMESTAMP
          );
          
          CREATE TABLE IF NOT EXISTS messages (
              id INT AUTO_INCREMENT PRIMARY KEY,
              message TEXT NOT NULL,
              user_id VARCHAR(255),
              created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
              INDEX idx_user_id (user_id),
              INDEX idx_created_at (created_at)
          );
          
          INSERT IGNORE INTO users (username, password) VALUES 
          ('admin', 'admin123'),
          ('testuser', 'test123');
          EOF
          
          echo "Database initialization completed!"
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "jiwoo1234!"
      restartPolicy: OnFailure
