apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiwoo-fastapi
  namespace: jiwoo
  labels:
    app: jiwoo-fastapi
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jiwoo-fastapi
  template:
    metadata:
      labels:
        app: jiwoo-fastapi
        version: v1
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: fastapi
        image: ktech4.azurecr.io/kltecho_jiwoo-fastapi:latest
        ports:
        - containerPort: 8000
        env:
        # OpenTelemetry 설정
        - name: OTEL_SERVICE_NAME
          value: "jiwoo-fastapi"
        - name: OTEL_SERVICE_NAMESPACE
          value: "jiwoo"
        - name: OTEL_DEPLOYMENT_ENVIRONMENT
          value: "dev"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://collector.lgtm.20.249.154.255.nip.io:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        # 애플리케이션 설정
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jiwoo-fastapi-service
  namespace: jiwoo
  labels:
    app: jiwoo-fastapi
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: jiwoo-fastapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jiwoo-fastapi-ingress
  namespace: jiwoo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: fastapi.4.230.144.92.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jiwoo-fastapi-service
            port:
              number: 8000
