controller:
  replicaCount: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

zookeeper:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

persistence:
  enabled: true
  size: 1Gi

service:
  type: ClusterIP

# 인증 비활성화
auth:
  enabled: false
