auth:
  enabled: true
  username: "jiwoo"
  password: "jiwoo1234!"
  database: "jiwoo_db"

primary:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

service:
  type: ClusterIP
