auth:
  enabled: true
  password: "New1234!"

architecture: standalone

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 1Gi

master:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
